proposed editorial fixes in -10
intarchboard/program-rfced-future pull request #153
Opened 2022-01-19 18:23 UTC by stpeter

2022-01-29 09:08 UTC, elear commented on draft-iab-rfcefdp-rfced-model.md
> -to the community in detail. The explanation might or might not be actionable.
Please do not remove this text.  It has a very specific meaning, which is that a proposal may be so fundamentally problematic that the CONCERN might not be clearable.

2022-01-29 09:09 UTC, elear requested changes
See comment.

2022-01-30 20:58 UTC, stpeter commented on draft-iab-rfcefdp-rfced-model.md
> -to the community in detail. The explanation might or might not be actionable.
See adjusted text in https://github.com/intarchboard/program-rfced-future/pull/153/commits/4e3a501018e685700262df0f4a8337db796369e9

2022-01-30 21:09 UTC, elear approved these changes

2022-02-01 14:40 UTC, merged