Fix some language nits
intarchboard/program-rfced-future pull request #75
Opened 2021-07-20 11:07 UTC by larseggert

2021-07-20 11:37 UTC, elear requested changes

2021-07-20 11:37 UTC, elear commented on draft-iab-rfcefdp-rfced-model.md
> +in a spirit of good faith and mutual understanding to achieving rough
I don't think this one's correct.

2021-07-20 11:37 UTC, elear commented on draft-iab-rfcefdp-rfced-model.md
> +the rfc-editor.org website, and other communication channels can be
Astonishingly, Lars' edit here is in accordance with Miriam Webster!!  Who knew??

2021-08-02 19:51 UTC, stpeter commented on draft-iab-rfcefdp-rfced-model.md
> +the rfc-editor.org website, and other communication channels can be
RFC 7322 (the RFC Style Guide) uses "website" so I suggest we keep this as-is.

2021-08-02 20:19 UTC, stpeter commented
I've made the appropriate changes in my local copy, so I'm going to close this one without merging.

2021-08-02 20:19 UTC, closed without merging